# Copyright (c)  2022-2023  Xiaomi Corporation
function(download_torch_libs)
  include(FetchContent)

  message(STATUS "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
  message(STATUS "CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")

  if(CMAKE_SYSTEM_NAME STREQUAL Linux AND CMAKE_SYSTEM_PROCESSOR STREQUAL x86_64)
    if(BUILD_SHARED_LIBS)
      if(GLIBCXX_USE_CXX11_ABI)
        include(torch-linux-x64-shared-cxxabi)
      else()
        include(torch-linux-x64-shared)
      endif()
    else()
      if(GLIBCXX_USE_CXX11_ABI)
        include(torch-linux-x64-static-cxxabi)
      else()
        include(torch-linux-x64-static)
      endif()
    endif()
  else()
    message(STATUS "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
    message(STATUS "CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")
    message(FATAL_ERROR "Only support Linux x64 at present. Will support other OSes later")
  endif()
  set(onnxruntime_SOURCE_DIR ${onnxruntime_SOURCE_DIR} PARENT_SCOPE)
endfunction()

download_torch_libs()
