name: linux

on:
  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Display PWD
        shell: bash
        run: |
          echo "pwd: $PWD"
          ls -lh
          du -h -d1 .

      - name: Install deps
        shell: bash
        run: |
          sudo apt-get install -y libprotobuf-dev

      - name: Build
        shell: bash
        run: |
          mkdir build

          cd build

          cmake \
            -D BUILD_SHARED_LIBS=ON \
            -D GLIBCXX_USE_CXX11_ABI=ON \
            ..
          make
          ls -lh ./bin

          readelf -d ./bin/main

          ./bin/main
