name: linux

on:
  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        lib-type: [shared, static]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Display PWD
        shell: bash
        run: |
          echo "pwd: $PWD"
          ls -lh
          du -h -d1 .

      - name: Install deps
        shell: bash
        run: |
          sudo apt-get install -y libprotobuf-dev

      - name: Build
        shell: bash
        run: |
          if [[ ${{ matrix.lib-type }} == "shared" ]]; then
            BUILD_SHARED_LIBS=ON
          else
            BUILD_SHARED_LIBS=OFF
          fi

          mkdir build

          cd build

          cmake \
            -D BUILD_SHARED_LIBS=$BUILD_SHARED_LIBS \
            ..

          make VERBOSE=1

          ./bin/main

      - name: Display dependencies
        shell: bash
        run: |
          ls -lh ./build/bin/main

          readelf -d ./build/bin/main

          ldd ./build/bin/main

      - name: Display torch lib file sizes
        shell: bash
        run: |
          ls -lh build/bin
          echo "---"
          ls -lh build/_deps/torch_libs-src/lib/
